### ISSUE TITLE
Why is this code not work on the Window? 

### ISSUE THREAD

**Issue by benthebear93** [lakehanne/keyence#2]
Hello, i am trying to Read the simple output data from the LJ-V7000 Sensor.
And i found this code but it doesn't work on the Window.
I changed few Socket function to suit window env but i only get 4 byte.

I tried this code on linux environment and it works fine.
i could just use the linux for the project but i want to know what is the problem.

I know this repo is old but if you have any idea, let me know. i would appreciate 

thx.

**Comment by robotsorcerer** [comment]
I did not test it on Windows, sorry. Feel free to try and send a PR.
