### ISSUE TITLE
Use ntohl instead of hand byte swapping

### ISSUE THREAD

**Issue by eudoxos** [lakehanne/keyence#4]
Hi, thank you for the code :) This is just a note from fellow network programmer: [ntohl](https://linux.die.net/man/3/ntohl) does the byte order conversions for you, no need for doing it [by hand](https://github.com/lakehanne/keyence/blob/master/src/src_c/LJV7_GetProfile.c#L50-L53). Cheers!

**Comment by robotsorcerer** [comment]
Good to know.

Thanks!



-----
Mercy buckets,
Lekan
